{% set name = "azure_batch" %}
{% set version = environ.get("PACKAGE_VERSION") %}
{% set source_url = environ.get("SOURCE_URL") %}
{% set source_sha256 = environ.get("SOURCE_SHA256") %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "{{ source_url }}"
  sha256: "{{ source_sha256 }}"

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vv"

requirements:
  host:
    - python 3.12.*
    - pip
    - setuptools >=61
    - wheel
  run:
    - python >=3.12,<3.14
    - azure-batch==14.2.0
    - azure-common==1.1.28
    - azure-core==1.30.1
    - azure-identity==1.17.1
    - azure-mgmt-compute==29.1.0
    - azure-storage-blob==12.20.0
    - azure_storage==0.0.14
    - coloredlogs==15.0.1
    - flask==3.0.3
    - python-dotenv==1.0.1
    - tqdm==4.66.4

test:
  source_files:
    - tests

  requires:
    - pytest==8.2.1
    - pytest-cov==5.0.0

  imports:
    - azure_batch

  commands:
    - AzureBatch -h
    - python -m pytest -v tests

about:
  home: https://github.com/OLC-LOC-Bioinformatics/AzureBatch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: >-
    Python tools for creating pools, jobs, and tasks in Azure Batch.
  description: |
    AzureBatch is a Python-based suite of tools for creating and managing
    pools, jobs, and tasks in an Azure Batch account.
  doc_url: https://github.com/OLC-LOC-Bioinformatics/AzureBatch
  dev_url: https://github.com/OLC-LOC-Bioinformatics/AzureBatch

extra:
  recipe-maintainers:
    - adamkoziol
