site_name: OLC Bioinformatics Azure Batch Library
site_url:  https://OLC-LOC-Bioinformatics.github.io/AzureBatch/
site_description: Python library for
repo_url:  https://github.com/OLC-LOC-Bioinformatics/AzureStorage/
edit_uri: edit/main/docs/
theme: readthedocs
